// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_project`, `due_timestamp`, `status_str`

Future<void> openReplica({required String dir}) =>
    RustLib.instance.api.crateApiTasksOpenReplica(dir: dir);

/// List tasks that have NOT been deleted. When `include_completed` is false, only
/// pending tasks are returned; when true, completed tasks are included as well.
/// Deleted, recurring, and unknown-status tasks are always excluded.
Future<List<TaskSummary>> listTasks({required bool includeCompleted}) => RustLib
    .instance
    .api
    .crateApiTasksListTasks(includeCompleted: includeCompleted);

Future<void> addTask({
  required String description,
  String? project,
  PlatformInt64? dueUnix,
  int? dueTimeMinutes,
}) => RustLib.instance.api.crateApiTasksAddTask(
  description: description,
  project: project,
  dueUnix: dueUnix,
  dueTimeMinutes: dueTimeMinutes,
);

/// Edit an existing task's description, project, and due date. A `None` project or
/// due date clears that field; `Some` sets it.
Future<void> modifyTask({
  required String uuid,
  required String description,
  String? project,
  PlatformInt64? dueUnix,
  int? dueTimeMinutes,
}) => RustLib.instance.api.crateApiTasksModifyTask(
  uuid: uuid,
  description: description,
  project: project,
  dueUnix: dueUnix,
  dueTimeMinutes: dueTimeMinutes,
);

Future<void> completeTask({required String uuid}) =>
    RustLib.instance.api.crateApiTasksCompleteTask(uuid: uuid);

/// Move a completed task back to pending.
Future<void> uncompleteTask({required String uuid}) =>
    RustLib.instance.api.crateApiTasksUncompleteTask(uuid: uuid);

Future<void> deleteTask({required String uuid}) =>
    RustLib.instance.api.crateApiTasksDeleteTask(uuid: uuid);

Future<void> syncTasks({
  required String url,
  required String clientId,
  required String secret,
}) => RustLib.instance.api.crateApiTasksSyncTasks(
  url: url,
  clientId: clientId,
  secret: secret,
);

class TaskSummary {
  final String uuid;
  final String description;
  final String? project;
  final PlatformInt64? dueUnix;

  /// "pending" or "completed". Deleted/recurring/unknown tasks are never returned.
  final String status;

  /// Completion time (Unix seconds), from taskchampion's "end" property. Set when a
  /// task is completed, cleared when it returns to pending. `None` for pending tasks.
  final PlatformInt64? endUnix;

  const TaskSummary({
    required this.uuid,
    required this.description,
    this.project,
    this.dueUnix,
    required this.status,
    this.endUnix,
  });

  @override
  int get hashCode =>
      uuid.hashCode ^
      description.hashCode ^
      project.hashCode ^
      dueUnix.hashCode ^
      status.hashCode ^
      endUnix.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaskSummary &&
          runtimeType == other.runtimeType &&
          uuid == other.uuid &&
          description == other.description &&
          project == other.project &&
          dueUnix == other.dueUnix &&
          status == other.status &&
          endUnix == other.endUnix;
}
